import type {
  InstrumentId,
  Pattern,
  Technique,
  TimeSignature,
} from "../../types/music";
const create = (
  id: string,
  name: string,
  instrument: InstrumentId,
  actions: Technique[],
  signature: TimeSignature = "4/4",
  stepsPerBeat = 2,
): Pattern => ({
  id,
  name,
  instrument,
  signature,
  stepsPerBeat,
  steps: actions.map((a, i) => ({
    actions: [a],
    velocity: i === 0 ? 1 : 0.78,
  })),
});
export const PATTERNS: Pattern[] = [
  create("g-basic", "Basic 4/4", "guitar", [
    "DOWN",
    "REST",
    "DOWN",
    "REST",
    "DOWN",
    "REST",
    "DOWN",
    "REST",
  ]),
  create("g-pop", "Pop", "guitar", [
    "DOWN",
    "REST",
    "DOWN",
    "UP",
    "REST",
    "UP",
    "DOWN",
    "UP",
  ]),
  create("g-ballad", "Ballad", "guitar", [
    "BASS",
    "PICK_3",
    "PICK_2",
    "PICK_1",
    "DOWN",
    "REST",
    "UP",
    "REST",
  ]),
  create("g-slow", "Slow Ballad", "guitar", [
    "BASS",
    "REST",
    "PICK_3",
    "PICK_2",
    "PICK_1",
    "REST",
    "PICK_2",
    "PICK_3",
  ]),
  create("g-rock", "Rock", "guitar", [
    "ACCENT_DOWN",
    "DOWN",
    "PALM_MUTE",
    "UP",
    "ACCENT_DOWN",
    "DOWN",
    "PALM_MUTE",
    "UP",
  ]),
  create("g-acoustic", "Acoustic Pop", "guitar", [
    "BASS",
    "PICK_3",
    "DOWN",
    "UP",
    "MUTE",
    "PICK_2",
    "DOWN",
    "UP",
  ]),
  create("g-bass", "Bass + Strum", "guitar", [
    "BASS",
    "REST",
    "DOWN",
    "UP",
    "BASS",
    "REST",
    "DOWN",
    "UP",
  ]),
  create("g-finger", "Fingerstyle Basic", "guitar", [
    "BASS",
    "PICK_3",
    "PICK_2",
    "PICK_1",
    "BASS",
    "PICK_3",
    "PICK_2",
    "PICK_1",
  ]),
  create("g-finger-ballad", "Fingerstyle Ballad", "guitar", [
    "BASS",
    "PICK_3",
    "PICK_2",
    "PICK_1",
    "PICK_2",
    "PICK_3",
    "HIGH",
    "MID",
  ]),
  create(
    "g-68",
    "Picking 6/8",
    "guitar",
    ["BASS", "PICK_3", "PICK_2", "PICK_1", "PICK_2", "PICK_3"],
    "6/8",
    1,
  ),
  create("g-palm", "Palm Mute", "guitar", [
    "PALM_MUTE",
    "PALM_MUTE",
    "SLAP",
    "UP",
    "PALM_MUTE",
    "PALM_MUTE",
    "SLAP",
    "UP",
  ]),
  create(
    "g-waltz",
    "Acoustic Waltz",
    "guitar",
    ["BASS", "REST", "DOWN", "UP", "DOWN", "UP"],
    "3/4",
  ),
  create("p-block", "Block", "piano", [
    "BLOCK",
    "REST",
    "REST",
    "REST",
    "BLOCK",
    "REST",
    "REST",
    "REST",
  ]),
  create("p-broken", "Broken", "piano", [
    "ROOT",
    "THIRD",
    "FIFTH",
    "THIRD",
    "ROOT",
    "THIRD",
    "FIFTH",
    "THIRD",
  ]),
  create("p-up", "Arpeggio Up", "piano", [
    "ROOT",
    "THIRD",
    "FIFTH",
    "TOP",
    "ROOT",
    "THIRD",
    "FIFTH",
    "TOP",
  ]),
  create("p-updown", "Arpeggio Up/Down", "piano", [
    "ROOT",
    "THIRD",
    "FIFTH",
    "TOP",
    "FIFTH",
    "THIRD",
    "ROOT",
    "REST",
  ]),
  create("p-ballad", "Ballad", "piano", [
    "ROOT",
    "FIFTH",
    "THIRD",
    "FIFTH",
    "ROOT",
    "FIFTH",
    "THIRD",
    "FIFTH",
  ]),
  create("p-pop", "Pop", "piano", [
    "OCTAVE",
    "REST",
    "BLOCK",
    "REST",
    "ROOT",
    "FIFTH",
    "BLOCK",
    "REST",
  ]),
  create("p-octave", "Octave", "piano", [
    "OCTAVE",
    "REST",
    "THIRD",
    "FIFTH",
    "OCTAVE",
    "REST",
    "BLOCK",
    "REST",
  ]),
];
export const actionLabel = (action: string) =>
  ({
    DOWN: "↓",
    UP: "↑",
    BASS: "B",
    MUTE: "×",
    PALM_MUTE: "PM",
    SLAP: "S",
    REST: "·",
    ACCENT_DOWN: "↓!",
    ACCENT_UP: "↑!",
    BLOCK: "●",
    ROOT: "R",
    THIRD: "3",
    FIFTH: "5",
    TOP: "8",
    OCTAVE: "8v",
    LOW: "Lo",
    MID: "Mi",
    HIGH: "Hi",
  })[action] ?? action.replace("PICK_", "P");
